2019-05-25 16:06:49,702 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-25 16:13:01,216 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-26 10:55:30,588 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-26 10:55:39,860 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:20:08,352 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:30:41,894 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:33:09,809 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:35:22,101 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:37:43,457 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-27 06:44:34,233 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-28 06:33:24,341 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-28 06:34:38,219 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-28 06:43:08,549 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:02:36,024 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:02:42,640 ERROR: Exception on /index [GET] [in /home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chad/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/chad/microblog/app/routes.py", line 31, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-05-30 11:04:00,392 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:07:06,574 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-30 11:09:42,022 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:45]
2019-05-31 06:09:03,304 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:12:22,557 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:17:59,531 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
2019-05-31 06:18:55,895 INFO: Microblog startup [in /home/chad/microblog/app/__init__.py:47]
